GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/3

###

GET http://localhost:3001/api/persons/100

###

DELETE http://localhost:3001/api/persons/3

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Kristaq Mehilli",
  "number": "068012378"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Arto Hellas",
  "number": "068012378"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "number": "068012378"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Kristaq Mehilli"
}